import {
  IsString,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsArray,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { ProductVariant as IProductVariant } from '@shared-types';
import { ProductVariantOptionDto } from './product-variant-option.dto';

export class ProductVariantDto implements IProductVariant {
  @IsString()
  @IsNotEmpty()
  id: string; // Assuming UUID generated by backend

  @IsString()
  @IsNotEmpty()
  sku: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ProductVariantOptionDto)
  options: ProductVariantOptionDto[];

  @IsNumber()
  @IsOptional()
  price?: number;

  @IsNumber()
  @IsNotEmpty()
  stockLevel: number;

  @IsString()
  @IsOptional()
  imageUrl?: string;
}
